// Copyright (C) 2026 pmm-dump-load authors
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, see <https://www.gnu.org/licenses/>.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"strings"

	"github.com/alecthomas/kingpin/v2"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"

	"pmm-dump-qan-sql/internal/metricsschema"
	"pmm-dump-qan-sql/internal/sqlexport"
)

var identRE = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

func main() {
	app := kingpin.New("pmm-dump-qan-sql",
		"Generate ClickHouse INSERT SQL from a pmm-dump QAN chunk (e.g. 0.tsv)")

	pmmVersion := app.Flag("pmm-version", "PMM major version: auto (detect from TSV width), pmm2, or pmm3").
		Default("auto").String()
	output := app.Flag("output", "Output .sql file path").Short('o').String()
	database := app.Flag("database", "ClickHouse database name in generated SQL").Default("pmm").String()
	table := app.Flag("table", "ClickHouse table name in generated SQL").Default("metrics").String()
	batchSize := app.Flag("batch-size", "Rows per INSERT statement").Default("100").Int()
	verbose := app.Flag("verbose", "Enable verbose logging").Short('v').Bool()

	tsvPath := app.Arg("tsv", "Path to pmm-dump ClickHouse chunk (e.g. source/ch/0.tsv)").Required().ExistingFile()

	kingpin.MustParse(app.Parse(os.Args[1:]))

	if *verbose {
		log.Logger = log.Output(zerolog.ConsoleWriter{Out: os.Stderr})
		zerolog.SetGlobalLevel(zerolog.DebugLevel)
	}

	if !identRE.MatchString(*database) || !identRE.MatchString(*table) {
		log.Fatal().Msg("--database and --table must be simple identifiers")
	}

	outPath := *output
	if outPath == "" {
		outPath = strings.TrimSuffix(*tsvPath, filepath.Ext(*tsvPath)) + ".sql"
	}

	version, scanTypes, err := resolveVersionAndScanTypes(*tsvPath, *pmmVersion)
	if err != nil {
		log.Fatal().Err(err).Msg("resolve metrics schema")
	}

	in, err := os.Open(*tsvPath)
	if err != nil {
		log.Fatal().Err(err).Msg("open TSV file")
	}
	defer in.Close() //nolint:errcheck

	out, err := os.Create(outPath)
	if err != nil {
		log.Fatal().Err(err).Msg("create output SQL file")
	}
	defer out.Close() //nolint:errcheck

	if _, err := fmt.Fprintf(out, "-- Generated by pmm-dump-qan-sql from %s (%s)\n\n", filepath.Base(*tsvPath), version); err != nil {
		log.Fatal().Err(err).Msg("write SQL header")
	}

	log.Info().
		Str("pmm", version.String()).
		Str("tsv", *tsvPath).
		Str("output", outPath).
		Int("columns", len(scanTypes)).
		Msg("generating SQL")

	rows, err := sqlexport.Generate(in, out, scanTypes, sqlexport.Options{
		Database:  *database,
		Table:     *table,
		BatchSize: *batchSize,
	})
	if err != nil {
		log.Fatal().Err(err).Msg("generate SQL")
	}

	log.Info().Int("rows", rows).Str("output", outPath).Str("pmm", version.String()).Msg("done")

	fmt.Println()
	fmt.Printf("Detected %s QAN dump (%d columns, %d rows).\n", version, len(scanTypes), rows)
	fmt.Println("Load into PMM ClickHouse from the PMM server host/container:")
	fmt.Println(metricsschema.ClickHouseImportCommand(version, outPath))
}

func resolveVersionAndScanTypes(tsvPath, versionFlag string) (metricsschema.Version, []reflect.Type, error) {
	flagVersion, err := metricsschema.ParseVersionFlag(versionFlag)
	if err != nil {
		return metricsschema.VersionUnknown, nil, err
	}

	version := flagVersion
	if version == metricsschema.VersionUnknown {
		version, err = metricsschema.DetectFromTSV(tsvPath)
		if err != nil {
			return metricsschema.VersionUnknown, nil, err
		}
		log.Info().Str("pmm", version.String()).Msg("auto-detected PMM version from TSV")
	}

	scanTypes, err := metricsschema.ScanTypes(version)
	return version, scanTypes, err
}
